### ISSUE TITLE
UTF-8 characters aren't supported

### ISSUE THREAD

**Issue by stef686** [tiebreak-wargames/tiebreak-issues#1]
UTF-8 characters currently aren't supported, especially when entering player names

**Comment by Gamingdevil** [comment]
Actually, it's not entirely clear which code set is used.
Characters that I've noticed are allowed, a.o.: " ( ç
Characters that don't work, a.o.: ' Polish and Scandinavian characters.

The database will also need to support these

**Comment by Gamingdevil** [comment]
"Rasmus Mølbak" works too

**Comment by stef686** [comment]
The database table for player data wasn't set to allow UTF-8 4-byte characters. I've updated this across all database tables and tested on a dummy event and all seems to be working fine now.

**Comment by Gamingdevil** [comment]
Alphanumeric characters all seem to be fixed.
There is still an issue with the `'` character, I assume this is because it denotes a string literal in SQL, and it will have to be escaped before entering into the database.

**Comment by stef686** [comment]
The `'` character can now be used in player names, that query wasn't being properly escaped!

**Comment by Gamingdevil** [comment]
Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'troglodytes', `email` = '' WHERE id = '43639'' at line 5

UPDATE `to_player` SET `club` = 'Belgium', `name` = 'Belgium Yellow-bellied sons o' troglodytes', `email` = '' WHERE id = '43639'

Filename: /var/www/website/legacy/website/website/models/players_model.php

Line Number: 1655

**Comment by Gamingdevil** [comment]
Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Andrea', `email` = '', `confirmed` = '0', `parent`' at line 6

UPDATE `to_player` SET `faction` = '9', `club` = '', `name` = 'Luca D'Andrea', `email` = '', `confirmed` = '0', `parent` = '43662', `member` = '13240' WHERE id = '43768'

Filename: /var/www/website/legacy/website/website/models/players_model.php

Line Number: 914
