### ISSUE TITLE
Player import hangs

### ISSUE THREAD

**Issue by stef686** [tiebreak-wargames/tiebreak-issues#4]
When importing players the page hangs

**Comment by Gamingdevil** [comment]
This could be the same as the character set issue. I tried to import 50 players at once, so it's not impossible that the set contained some character that didn't work.

**Comment by stef686** [comment]
That's a good point, worth re-testing after #1 has been resolved

**Comment by stef686** [comment]
This issue could have been 2 things. The character issue from #1 and also an issue when factions aren't entered into the upload box (or unknown/misspelt factions)

I've added a fix for the factions which will now default to no faction unless a match is found.

Therefore closing this issue as resolved.
